"""Change language field length in user model

Revision ID: b4f5302bda83
Revises: 209d681ce879
Create Date: 2025-10-31 14:00:51.485635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4f5302bda83"
down_revision: str | Sequence[str] | None = "209d681ce879"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "language",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "language",
        existing_type=sa.String(length=2),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
