"""Change language field length in user model

Revision ID: 40c6ff79ca20
Revises: b4f5302bda83
Create Date: 2025-11-06 22:34:50.447951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40c6ff79ca20"
down_revision: str | Sequence[str] | None = "b4f5302bda83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "language",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "language",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
