"""Add language fields to user model

Revision ID: 209d681ce879
Revises: dc84df0db31a
Create Date: 2025-10-30 12:14:12.518387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "209d681ce879"
down_revision: str | Sequence[str] | None = "dc84df0db31a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("language", sa.String(length=10), nullable=True))
    op.add_column("users", sa.Column("cefr_level", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cefr_level")
    op.drop_column("users", "language")
    # ### end Alembic commands ###
